apiVersion: v1
kind: Pod
metadata:
  name: graceful-exit
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Starting...'; sleep 3600"]
