apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-with-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: registry.redhat.io/rhel8/postgresql-13
        env:
        - name: POSTGRESQL_USER
          value: "user"
        - name: POSTGRESQL_PASSWORD
          value: "password"
        - name: POSTGRESQL_DATABASE
          value: "mydb"
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/postgresql
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo 'PostgreSQL is shutting down' >> /var/log/postgresql/shutdown.log"]
        
      - name: logger
        image: busybox
        command: ["/bin/sh", "-c", "tail -F /var/log/postgresql/shutdown.log"]
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/postgresql

      volumes:
      - name: log-volume
        emptyDir: {}
